name: dotnetCi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        shell: bash
        run: |
          #tag="$(git describe --tags --abbrev=0)"
          release_name="FreshMeat-beta"
          dotnet publish FreshMeat/FreshMeat.csproj -c Release -o "$release_name"        
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "FreshMeat*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
